[package]
name = "mtl-info"
version = "0.2.0"
authors = ["Patrick Metcalfe <git@patrickmetcalfe.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
clap = "~2"
log = "~0"
simple_logger = "~1"
colored = "~1"
